### PR TITLE
fix(Issue-571): Updated partners slug page to use <pre> tags for about and short description.

### LINKED ISSUE #571: Partner detail "About Us" doesn't show line breaks
**Describe the bug**
In a partners' detailed page About Us doesn't respect carriage returns/line feeds not allowing the partner to add a simple break to thier about us paragraph.  I am assume this can be wrapped in a `pre` tag like other sections have.

**To Reproduce**
1. Go to https://www.thatconference.com/partner/do-it-best-corp
1. Noticed that the About US paragraph is a large chunk of text, not three separated pieces.

**Expected behavior**
About Us text added for a partner which has a line feed in it should show that on the web page

**Screenshots**
About Us in Firestore:
image

About Us on site:
image

**Device(s)/Browser(s) this is occurring on**
any

### PR DESCRIPTION
**Pull request by kburnell**
### Description

- Updated partners slug page to use `<pre>` instead of `<p>` for about us and short description so basic formatting is preserved.

- While ensuring there was a shared global pre style I noticed that the shared pre and paragraph styles where duplicated so I refactored to use a styled css to reduce redundancy.

Fixes #571 

### Screenshots (if appropriate):
Issue571_After

### Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

### How Has This Been Tested?
I tested this by viewing the partner mentioned in the bug, /partner/do-it-best-corp as well as other partners I knew had data such as, /partner/navitus-health-solutions and /partner/NVISIA to ensure all looked good.

I also confirmed other views that use the shared pre style such as, /wi/2021/jobs, where not impacted negatively by this change.

### Checklist:

- [N/A] I have updated the documentation if necessary
- [N/A] I have updated the stories as necessary
- [N/A] I have updated the specs necessary

### CODE REVIEW

File: components/shared/StandardStyles.js [hunk 1]
```diff
@@ -40,16 +40,12 @@ export const StyledP = styled.p`
...
-  line-height: 1.6;
-  font-size: 1.5rem;
+export const StyledP = styled.p`
+  ${ParagraphAndPreSharedStyles}
+`;
 
-  ${below.med`
-    margin-top: 0;
-  `};
+export const StyledPre = styled.pre`
```
Comment (saragibby) [inline components/shared/StandardStyles.js:47]: Looks like this component is used on `JobListing` and `SlimSession` (which I want to say was used in voting). It looks like it for sure needs the font-size there, or included in this component. I believe font-weight too but not sure. And, you could include the height: auto here too actually.

Comment (kburnell) [reply components/shared/StandardStyles.js:47]: @saragibby I tested both of those and noted in the PR.  Not sure why they would need to change as it is the exact same code I just extracted in to a shared style.

**Comment by csell5** [comment]
#### 📝Changed routes:


| [**/partner/\[slug\]**](https://that-website-git-kb-issue-571.that-conference.now.sh/partner/[slug]) |
|:-:|
|<a href="https://that-website-git-kb-issue-571.that-conference.now.sh/partner/[slug]">Screenshot of /partner/[slug]</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/05B4K01HowNpy6qpTJp_JX7k4UQ_.png">(view full size)</a> |







Commit e430977e837ae9d15f4c8275fb25e6454c5fb995 (https://that-website-git-kb-issue-571.that-conference.now.sh).
